<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>promise学习，基于node环境</title>
</head>

<body>

</body>
<script>
    //promise是支持es6的浏览器自带的一个方法，使用前先new,参数需要传一个结构函数
    //promise是同步执行的函数,在promise中执行异步函数
    //只有成功onFulfilled和失败onRejected两种状态，resolve和reject触发两种状态--可接受一个参数，用.then()进行注册
    // 一：
    let oP = new Promise((resolve, reject) => {
        console.log(0);
        setTimeout(() => {
            Math.random() * 100 > 60 ? resolve('ok') : reject('no');
        }, 100)
    });
    console.log(1);
    oP.then((val) => {
        console.log(val);
    }, (reason) => {
        console.log(reason);
    })


    // 注意.then()方法是异步执行的，和setTimeout一样,那两者谁先执行呢
    // 二：
    setTimeout(() => {
        console.log("setTime");
    }, 0)

    let oP2 = new Promise((resolve, reject) => {
        console.log(0);
        resolve(2);
    });
    console.log(1);
    oP2.then((val) => {
        console.log(val);
    }, (reason) => {
        console.log(reason);
    })
    // 分析：
    //      因为Promise是同步, 如果.then()是同步 所以输出顺序是：0 2 1 setTime
    //      如果Promise是同步, 如果.then()是异步，又因为setTimeout比resolve先放入执行队列，所以输出顺序是：0 1 setTime 2
    //      实际输出：0 1 2 setTime
    //      因为Promise是同步,.then()也是异步,
    //          setTimeout和ajax一样是宏任务,.then()是微任务,虽然宏任务比微任务先放入执行队列，但是微任务有优先执行权,所以先执行resolve()

    // 关于promise的链式调用
    // 三：
    let oP3 = new Promise((resolve, reject) => {
        setTimeout(() => {
            Math.random() * 100 > 60 ? resolve('及格') : reject('挂科');
        }, 100)
    })
    // oP3.then((val) => {
    //         console.log(val);
    //     },(result) => {
    //         console.log(result);
    // }).then((val) => {
    //     console.log("OK then2:",val)
    // },(result) => {
    //     console.log("NO then2:",result);
    // })   
    //---------------->  这段代码执，不管上一段是成功还是失败，都会执行第二段链式的成功函数，
    //                       并且val为undefined,因为下一段接收的参数是上一段链式的返回值,如下：

    // oP3.then((val) => {
    //         console.log(val);
    //         return val;
    //     },(result) => {
    //         console.log(result);
    //         return result;
    // }).then((val) => {
    //     console.log("OK then2:",val)           // -------> 始终执行OK,val值取决于上一段链式的返回值
    // },(result) => {
    //     console.log("NO then2:",result);
    // });

    // 如果返回值是promise对象：
    // oP3.then((val) => {
    //     console.log(val);
    //     return new Promise((resolve,reject) => {
    //         resolve("成功");
    //     });
    // }, (result) => {
    //     console.log(result);
    //     return new Promise((resolve,reject) => {
    //         reject("失败");
    //     });
    // }).then((val) => {
    //     console.log("OK then2:", val)
    // }, (result) => {
    //     console.log("NO then2:", result);
    // });
    // 此时下一段链式的执行情况就取决于上个链式的返回值中的promise是成功还是失败，如果是成功就执行下段中的成功，否则执行下段中的失败

    // .then()中不管是在成功还是失败的方法中只要抛出错误throw new Error();只要该方法(不管是成功还是失败)执行就都会执行下段链式中的失败方法：
    oP3.then((val) => {
        console.log(val);
        throw new Error("错误！");
        return val;
    }, (result) => {
        console.log(result);
        return result;
    }).then((val) => {
        console.log("OK then2:", val)
    }, (result) => {
        console.log("NO then2:", result);
    });
</script>

</html>